result: int:16
thrown: NoExceptionThrown
